#!/bin/sh

while true; do
	sleep 60

pid=$(ps | awk '/[v]2ray --config/{print $1}')

if [ "$pid" == "" ]; then
/tmp/v2ray/start.sh
echo "[V2Ray restarted]"
else
echo ""
echo "[V2Ray started]"
fi

done
